import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pedro Soares | Websites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-mini.svg" />
      </Head>
      <div>
        <h1 className="text-4xl">hello word</h1>
      </div>
    </>
  );
}
