import Hero from "@/components/homeSections/hero";
import NewsLetter from "@/components/homeSections/newsLetter";
import Projects from "@/components/homeSections/projects";
import PurposeCards from "@/components/homeSections/purposeCards";
import SplitSection from "@/components/homeSections/splitSection";
import Testimonials from "@/components/homeSections/testionails";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pedro Soares | Websites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-mini.svg" />
      </Head>
      <>
        <Hero />
        <PurposeCards />
        <SplitSection />
        <Projects />
        <Testimonials />
        <NewsLetter />
      </>
    </>
  );
}
